### ISSUE TITLE
Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by knowbody** [argyle-systems/argyle-link-sdk-react-native#9] opened 2020-04-23 07:27 UTC
There are times when we get this error via Sentry, and I'm wondering if this is something on your side that needs fixing. It happens when Argyle's screen is on and user taps on any of the Providers. I cannot reproduce it so pasting the logs from Sentry below:

![image](https://user-images.githubusercontent.com/3802023/80071056-49c2e080-8544-11ea-9697-23bce2b05372.png)

**Comment by Varnius** [comment] 2020-04-23 09:38
Thanks for the report, we will investigate.

**Comment by Varnius** [comment] 2020-05-01 12:56
@knowbody Hi, we could not reproduce this. Do you still see it happening?

**Comment by knowbody** [comment] 2020-05-05 12:49
yes we keep getting them, not very often but in the last week we had 7 occurrences:

![image](https://user-images.githubusercontent.com/3802023/81067798-8cd76900-8edf-11ea-83f3-2c7922e1a5b9.png)

**Comment by Varnius** [comment] 2020-07-29 13:38
Closing as non-reproducible Feel free to reopen if you find a way to replicate the issue.

**Closed by Varnius** 2020-07-29 13:38 UTC

**Comment by nikolaydevico** [comment] 2020-10-02 14:00
@Varnius Hi, I have the same issue
It happened when I tried to run application on device, iphone 7 iOS 13.7, I'm building the app with xcode 11.7

**Comment by Varnius** [comment] 2020-10-02 15:30
@nikolaydevico Hey, feel free to reopen the issue if you are aware of the way to consistency reproduce this.
